name: Psalm Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  psalm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Install Psalm
        run: composer require --dev vimeo/psalm

      - name: Init Psalm (kalau belum ada psalm.xml)
        run: vendor/bin/psalm --init || true

      - name: Run Psalm with security analysis
        run: vendor/bin/psalm --taint-analysis --output-format=github --shepherd --stats --threads=4
